blogdoleite/about/urls.py
from django.urls import path 
from . import views

app_name = 'about'

urlpatterns = [
    path('',views.about_index, name='about_index'),
]

blogdoleite/blogdoleite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core')),#Página incial. Importa o arquivo url dentro do diretório core
    path("about/", include('about.urls', namespace="about"))
]

blogdoleite/core/urls.py
from django.urls import path 
from . import views

#A estrutura de urls é como uma escada. O arquivo urls principal importa os arquivos urls dos apps e estes podem possuir outros caminhos urls.

app_name = 'core' #Essa variável tem que ter o mesmo nome que foi declarado no namespace. A variável é opcional.

urlpatterns = [
   path('',views.index, name='index'),
   path('post/<int:id>/',views.detail, name='detail'),
]

blogdoleite/about/models.py
from django.db import models

# Create your models here.

blogdoleite/core/models.py
from django.db import models
from django.utils.text import slugify #Biblioteca necessária para gerar as slugs automaticamente
from ckeditor.fields import RichTextField
# Create your models here.
#O Django cria um id automatico no banco de dados

class Post(models.Model):
    title = models.CharField('Título',max_length=150, blank=False, null=False)

    resume = models.TextField(default='')

    content = RichTextField()
    #content = models.TextField('Conteúdo', blank=False, null=False)
    date_published = models.DateTimeField('Data de publicação', auto_now=True) #Auto_now_add é utilizado para salvar as datas de modificações
    slug = models.SlugField('Slug', editable=False)#url baseada no título

    def __str__(self): 
        return self.title #Melhora a vizualização no banco de dados. Mostra o titulo

    def save(self, *args, **kwargs):#Cria a slug automaticamente
        value = self.title #salva o titulo na variável
        self.slug = slugify(value, allow_unicode=True) #Cria o slug a partir do título
        '''
        if(Post.objects.filter(slug = self.slug)
            self.slug += '--1'
        '''
        super().save(*args, **kwargs) #Segue o caminho normal após salvar

blogdoleite/about/views.py
from django.shortcuts import render
# Create your views here.
def about_index(request):
    return render(request, 'about/about_index.html') 

blogdoleite/core/views.py
from django.shortcuts import render
from .models import Post
# Create your views here.
def index(request):
    posts = Post.objects.all().order_by('-date_published')
    data = {
        'post_list': posts,
    }
    return render(request, 'core/index.html',data) #busca o arquivo index.html dentro do diretório templates/core/index.html.

def detail(request, id): #id é a variável que irá filtrar o post
    post = Post.objects.get(id = id)
    data = {
        'post': post
    }
    return render(request, 'core/detail.html', data)

blogdoleite/about/templates/about/about_index.html
{% extends '..\..\core\templates\core\base.html' %}
{%block content%}

         <section class="section">
            <h1 class="title has-text-centered">
                Lucas Leite
            </h1> <!--Entra dentro do objeto Post-->
            <h2 class="subtitle has-text-centered">
                Estudante de engenharia elétrica tentando fazer um blog por meio do Django. 
            </h2>
        </section>
{%endblock%}

blogdoleite/core/templates/core/base.html
{%load static%} <!--Carrega os arquivos estáticos-->
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{%static 'core/bulma.css'%}">
    <link rel="stylesheet" href="{%static 'core/footer.css'%}">
    <link rel="stylesheet" href="{%static 'core/wysiwyg.css'%}">
    <link rel="stylesheet" href="{%static 'core/card.css'%}">
    <title>Blog do Leite</title>

</head>

<body>
    <section class="hero is-medium is-info">
        <div class="hero-body">
        <p class="title has-text-centered">
        Bem vindo ao Blog do Leite
        </p>
        <p class="subtitle has-text-centered">
        Blog criado no tutorial de Django
        </p>
        </div>
        <div class="card"> <!--Cria um menu para navegação-->
            <footer class="card-footer">
                <a href="{% url 'core:index' %}" class="card-footer-item"><strong>Posts</strong></a>
                <a href="{% url 'about:about_index' %}" class="card-footer-item"><strong>About</strong></a>
            </footer>
        </div>
    </section>

    {% block  content %}
    {% endblock  %}

    <footerlass="footer">
        <div class="content has-text-centered">
            <p>
            <strong>Blog do Leite</strong> by Lucas Leite
            </p>
        </div>
    </footer>

</body>
</html>

blogdoleite/core/templates/core/detail.html
{% extends './base.html' %}
{%block content%}

     <section class="section">
        <h1 class="title">{{post.title}}</h1> <!--Entra dentro do objeto Post-->
        <div class="wysiwyg">
        {{post.content|safe}} <!--Se não tiver a tag pipe,"|", o texto aparecerá com formatações html-->
        </div>
    </section>


{%endblock%}
  
  

blogdoleite/core/templates/core/index.html
{% extends './base.html' %}
{%block content%}

    {%if post_list %} 
        {% for post in post_list %}
         <section class="section">
            <h1 class="title"><a href= "{% url 'core:detail' post.id %}">{{post.title}}</a></h1> <!--Entra dentro do objeto Post-->
            <h2 class="subtitle">
                {{post.resume}}
            </h2>
        </section>
        {% endfor %}
    {% else %}
        <h2>Nao tem nada</h2>
    {%endif%}


{%endblock%}
  
 